cfssl:
  restart: always
  # entrypoint: ["sh", "-c", "sleep 204728384" ]
  build: ./cfssl
  expose:
    - "8000"
    - "8888"
    - "8889"
  links:
    - postgres:postgres
  volumes:
    - /root/infra/apt-miss.com:/root/infra
  environment:
    DEBUG: 'False'
lemur-web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - cfssl:cfssl
  volumes:
	# lets nginx use static lemur content
    - /usr/local/src/lemur/lemur/static/dist
  environment:
    DEBUG: 'False'
    LEMUR_CONF: /usr/local/src/lemur/lemur.conf.py
    LEMUR_TARGET: release
lemur-nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - lemur-web
  links:
    - lemur-web
    - lemur-web:web

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
